---
title: "Material"
---

## Core Material

* [Syllabus](syllabus.qmd)  
* [Formulae](formulae.qmd)  
* [Calendar](calendar.qmd)  

## Slides

1. [Central Limit Theorem](slides/01_CLT_slides.qmd) [PDF](PDF/01_CLT_slides.pdf)
2. [Sampling Distributions](slides/02_Sampling_Distributions.qmd) [PDF](PDF/02_Sampling_Distributions.pdf)
3. [Point Estimation](slides/03_point_estimation.qmd) [PDF](PDF/03_point_estimation.pdf)
4. [Interval Estimation I](slides/04_interval_estimation_part1.qmd) [PDF](PDF/04_interval_estimation_part1.pdf)
5. [Interval Estimation II](slides/05_interval_estimation_part2.qmd) [PDF](PDF/05_interval_estimation_part2.pdf)
6. [Hypothesis Testing Introduction, *p-value*](slides/06_hypothesis_testing_intro_pvalue.qmd) [PDF](PDF/06_hypothesis_testing_intro_pvalue.pdf)
7. [Hypothesis Testing for $\mu$ and $\sigma^2$, mean difference](slides/07_hypothesis_testing_tests_mean_var_mdiff.qmd) [PDF](PDF/07_hypothesis_testing_tests_mean_var_mdiff.pdf)
8. [Linear Regression Introduction](slides/08_Linear_Regression_Introduction_OLS.qmd) [PDF](PDF/08_Linear_Regression_Introduction_OLS.pdf)
9. [Linear Regression Fit](slides/09_Linear_Regression_GoodnessOfFit_MLR.qmd) [PDF](PDF/09_Linear_Regression_GoodnessOfFit_MLR.pdf)
10. [Linear Regression Inference](slides/10_Linear_Regression_Inference_Validation.qmd) [PDF](PDF/10_Linear_Regression_Inference_Validation.pdf)


## Applied Lectures R

We are going to try to apply what we have been learing in R. You can access a platform that will let you play with it in [Jupyter](https://jupyter.org).

1. [SLR](slides/08_R_SLR.qmd)

## Exercises

1. [Central Limit Theorem](exercises/01_Central_Limit_Theorem.qmd)
2. [Sampling Distributions](exercises/02_Sampling_Distributions.qmd)
3. [Point Estimation](exercises/03_Point_Estimation.qmd)
4. [Interval Estimation](exercises/04_Interval_Estimation.qmd)
5. [Hypothesis Testing](exercises/05_Hypothesis_Testing.qmd)
6. [Linear Regression](exercises/06_Linear_Regression.qmd)